#! /bin/sh

# If refreshing bspwm, remove all previous rules to prevnt doubling up.
bscp rule -r "*"

# feh --recursive --randomize --bg-fill ~/.config/wallpapers
feh --bg-fill ~/.config/wallpapers/catwall.jpg

# Polybar
$HOME/.config/polybar/launch.sh

# mpd & # music player daemon-you might prefer it as a service though
sxhkd &
picom -b &
dunst &
unclutter &
fcitx -d &

killall bspswallow
pidof bspswallow || bspswallow &

# We look for a non-laptop monitor to use for default, but use the laptop
# screen (LVDS) if there's nothing else. This is because I assume that if you
# have an extra screen attached to a laptop, you want to use that.
mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

# Start workspaces on the main monitor.
bspc monitor $mainmonitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

# bspc rule -a Brave-browser:brave-browser desktop='^2'
# bspc rule -a discord desktop='^3'
bspc rule -a Zathura state=tiled
# bspc rule -a Zathura:org.pwmt.zathura state=tiled
bspc rule -a mpv state=fullscreen

# Dracula colors for borders
bspc config normal_border_color "#4B4C90"
bspc config active_border_color "#ff79c6"
bspc config focused_border_color "#ff79c6"
bspc config presel_border_color "#9C5A75"
